### ISSUE TITLE
A Burlesque Uchronian Mission

### ISSUE THREAD

**Issue by WhiteFangs** [NaNoGenMo/2020#51]
This year... *Hans Zimmeresque big bass BWOOOONG of blockbuster movies trailer*
In my NaNoGenMo intent... *bwooong*
I will generate... *bwoooong*

### A PROPER READABLE NOVEL.

Or so I hope.

**The concept:** An algorithm's random game of [A Better World](http://abw.blue/) rearranged into a novel.
**The story:** Humanity is in danger. A timetravelling agent needs to go back in time and alter the course of history to prevent that danger from happening.
**The catch:** Every change he makes snowballs into even more alterations of humanity's history, so he needs to make even more changes to prevent things from spiralling into madness.
**The tone:** Burlesque, absurd comedy with humour on bureaucracy and things getting out of hand (think Rick & Morty style)
**The generated parts:** All the game's text elements could be used as well as portions of rule-based generated text to tie things up in each chapter.
**The structure:** Every chapter of the novel is an event modification in the game. The character first acknowledges the altered timeline of humanity and his options of events he could alter. After selecting one, he gathers information about that event from various sources and lays out the two choices he has for altering this event. He hesitates then chooses one. He gets a result, be it an automated report from the future or his manager's comments. He contemplates the new timeline of humanity after his mission. Depending on the outcome (karma difference between then and now), it could be a good step forward for humanity or a bad direction. In any case, the chapter ends with a cliffhanger on a new event in humanity's timeline that WAS NOT SUPPOSED TO BE THERE OH DAMN WHAT DID HE DO??? Well, he'll try to correct it in the next chapter.

I'm gonna focus on French for the first version as I will be more comfortable with the language for the parts I have to write as well as the tone but I might do an English one afterwards if I have time and motivation.

### Roadmap

- [x] Ask the game's author permission to use his work and texts
- [x] Sketch the big pictures of what the project is about
- [ ] Write the program that plays the game and gathers relevant bits of text on the way
- [ ] Write the incipit and ending
- [ ] Define the rule-based text portions that tie up with the game's texts
- [ ] Write the rule-based generative grammar for these text portions
- [ ] Generate the novel chapter by chapter

**Comment by verachell** [comment]
Wow this sounds so cool! Looking forward to seeing it!

**Comment by WhiteFangs** [comment]
Here is the repo. I'm planning to finish the french version by the end of the month, not sure about the english one though.

**Comment by WhiteFangs** [comment]
Aaaaaand done!

Code is here: https://github.com/WhiteFangs/agent-3000
Output is here: http://louphole.com/divers/agent-3000/output.html

I won't have the time to do it in English this time but it was a fun trial!
